version: '3'

services:

  todoback:
    image: todobackend:latest
    ports:
      - 3001:3001

  todofront:
    image: todofrontend:latest
    ports:
      - 3000:3000
    depends_on:
      - "todoback"
    environment:
      REACT_APP_API_HOST: todoback

  todotests:
    image: todotests:latest
    environment:
      FRONT_HOST: todofront
    depends_on:
      - "todofront"
      - "todoback"